//npmconst functions = require("firebase-functions");
const express  = require('express');
var cors = require('cors');
const { urlencoded } = require('express');
const app = express();
const connectionSettings = require('./connection');
const userRoute = require('./routes/user');
const courseRoute = require('./routes/course');
const dashboardRoute = require('./routes/dashboard');
const studentRoute = require('./routes/student');
const consultantRoute = require('./routes/consultant');
app.use(cors());
app.use(urlencoded({limit: '25mb',extended: true}));
app.use(express.json({limit: '25mb'}));
app.use('/user',userRoute);
app.use('/courses',courseRoute);
app.use('/dashboard',dashboardRoute);
app.use('/student',studentRoute);
app.use('/consultant',consultantRoute);
app.connect(connectionSettings)
module.exports = app;